# Generated by Django 4.2.30 on 2026-06-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], max_length=10)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('1d', '1 Day'), ('1w', '1 Week'), ('1mo', '1 Month')], max_length=5)),
                ('prediction_date', models.DateTimeField(help_text='When the prediction was originally made')),
                ('target_date', models.DateTimeField(help_text='The date/time the prediction was for')),
                ('predicted_price', models.FloatField()),
                ('actual_price', models.FloatField()),
                ('predicted_direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=5)),
                ('actual_direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=5)),
                ('absolute_error', models.FloatField(help_text='|predicted - actual|')),
                ('percentage_error', models.FloatField(help_text='|predicted - actual| / actual  * 100')),
                ('direction_correct', models.BooleanField(default=False, help_text='True when the predicted direction matched the actual direction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prediction Verification',
                'verbose_name_plural': 'Prediction Verifications',
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['metal', 'timeframe'], name='oracle_pred_metal_366775_idx'), models.Index(fields=['prediction_date'], name='oracle_pred_predict_ec3c37_idx')],
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], max_length=10)),
                ('timeframe', models.CharField(choices=[('1d', '1 Day'), ('1w', '1 Week'), ('1mo', '1 Month')], max_length=5)),
                ('strategy', models.CharField(choices=[('rsi', 'RSI'), ('macd', 'MACD'), ('composite', 'Composite Signal'), ('sentiment', 'Sentiment Signal')], max_length=20)),
                ('horizon', models.CharField(choices=[('1d', 'Next Day'), ('1w', 'Next Week'), ('1mo', 'Next Month')], max_length=5)),
                ('accuracy', models.FloatField(help_text='Percentage of predictions that matched the actual direction (0–100)')),
                ('win_rate', models.FloatField(help_text='Percentage of trades that were profitable (0–100)')),
                ('total_trades', models.IntegerField(help_text='Number of trade signals evaluated')),
                ('avg_gain', models.FloatField(help_text='Average percentage gain on winning trades')),
                ('avg_loss', models.FloatField(help_text='Average percentage loss on losing trades (stored as positive number)')),
                ('profit_factor', models.FloatField(help_text='Gross profit / Gross loss  (>1 is profitable)')),
                ('max_drawdown', models.FloatField(default=0.0, help_text='Maximum peak-to-trough decline as a percentage')),
                ('sharpe_ratio', models.FloatField(default=0.0, help_text='Risk-adjusted return (annualised, assuming 0 risk-free rate)')),
                ('total_return', models.FloatField(default=0.0, help_text='Total percentage return over the backtested period')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backtest Result',
                'verbose_name_plural': 'Backtest Results',
                'ordering': ['-created_at'],
                'unique_together': {('metal', 'timeframe', 'strategy', 'horizon')},
            },
        ),
    ]
