# Generated by Django 4.2.30 on 2026-06-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0002_predictionverification_backtestresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricebar',
            name='timeframe',
            field=models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('1d', '1 Day'), ('1w', '1 Week')], db_index=True, max_length=5),
        ),
    ]
