# Generated by Django 4.2.30 on 2026-06-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0004_alter_prediction_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionverification',
            name='previous_price',
            field=models.FloatField(default=0, help_text='Market price at the time the prediction was generated'),
        ),
        migrations.AlterField(
            model_name='predictionverification',
            name='actual_direction',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('sideways', 'Sideways')], default='up', max_length=10),
        ),
        migrations.AlterField(
            model_name='predictionverification',
            name='predicted_direction',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('sideways', 'Sideways')], default='up', max_length=10),
        ),
    ]
